# https://hub.docker.com/_/mysql 에서 mysql 컨테이너 구성 위한 도커 컴포즈 파일
version: '4.3.0'   # 도커 엔진 버전
services:
  mysql:
    container_name: mysql_local
    image: mysql
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul